### ISSUE TITLE
Residence cannot block interact event of Mod item

### ISSUE THREAD

**Issue by CatMe0w** [bekvon/Residence#104]
Take AE2 Mod as a example, the mod sends custom packets that pypasses cauldron/bukkits event system. Select the quartz wrench item and HOLD LSHIFT TO RIGHT CLICK THE BLOCK OF THIS MOD, this block will drop without any residence permissions.

**Comment by CatMe0w** [comment]
Holy shit how beautiful you did, Residence need purchase for use now, and you even not to look these issue, what a nice work you did :-1:

**Comment by Zrips** [comment]
There is no support for mod's and they are completely different than plugins, this plugin is made for bukkit/spigot so don't expect it to fully work with forge moded servers.
