### ISSUE TITLE
[Bug] can't protect chest for residence

### ISSUE THREAD

**Issue by nicklly** [bekvon/Residence#156]
![SN7VWCL(X}GDK4FOSB}P9](https://user-images.githubusercontent.com/17716585/103353597-3826d500-4ae4-11eb-9fb3-aab96509c58b.jpg)
![QYEX83ALA363CB4X 5@GL4W](https://user-images.githubusercontent.com/17716585/103353604-3a892f00-4ae4-11eb-8826-04f008cb25d1.jpg)
![PR%DOX_EJ7VZWF(O6Y} ZZQ](https://user-images.githubusercontent.com/17716585/103353733-8b992300-4ae4-11eb-8115-e61e937e3ff2.jpg)

As the picture shows.... I stood outside the residence, holding the boat in my right hand, and from outside the territory, I can directly open the box on the edge of the residence

I using plugin version is 4.9.1.9
but try update to 4.9.2.2 the bug is still exist

**Comment by Jakush** [comment]
What you fixed?
